let b=4;

try{
    let a = 2 +b;

} catch(e){
    console.log(e);
}

//tenta executar o bloco de codigo que tem no try e se der algum erro ali ele pega o erro e imprime